<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import RecipeCard from '@/components/Recipes/RecipeCard.vue';
import { ref, onMounted, watch } from 'vue';
import { Input } from '@/components/ui/input';
import axios from '@/lib/axios';
import { route } from '@/lib/route';

interface Recipe {
    id: number;
    title: string;
    slug: string;
    description: string;
    image: string | null;
    cuisine: string;
    difficulty: string;
    prep_time: number;
    cook_time: number;
}

const recipes = ref<Recipe[]>([]);
const loading = ref(true);
const search = ref('');

const fetchRecipes = async () => {
    loading.value = true;
    try {
        const response = await axios.get('/recipes', {
            params: { search: search.value }
        });
        recipes.value = response.data.data || response.data || [];
    } catch (error) {
        console.error('Failed to fetch recipes:', error);
        // Mock data fallback
        recipes.value = [
            { id: 1, title: 'Mock Italian Pasta', slug: 'mock-italian-pasta', description: 'Delicious pasta dish', image: null, cuisine: 'Italian', difficulty: 'easy', prep_time: 15, cook_time: 20 },
            { id: 2, title: 'Mock Asian Stir Fry', slug: 'mock-asian-stir-fry', description: 'Quick stir fry', image: null, cuisine: 'Asian', difficulty: 'medium', prep_time: 10, cook_time: 15 },
        ];
    } finally {
        loading.value = false;
    }
};

onMounted(fetchRecipes);

// Debounced search
let searchTimeout: any;
watch(search, () => {
    clearTimeout(searchTimeout);
    searchTimeout = setTimeout(fetchRecipes, 500);
});

const breadcrumbs = [
    { title: 'Dashboard', href: route('dashboard') },
    { title: 'Recipes', href: route('recipes.index') },
];
</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbs">
        <Head title="Browse Recipes" />

        <div class="py-12 px-6 max-w-7xl mx-auto">
            <div class="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
                <div>
                    <h1 class="text-4xl font-bold text-white mb-2">Explore <span class="text-gradient">Recipes</span></h1>
                    <p class="text-gray-400">Discover delicious meals generated by AI.</p>
                </div>
                
                <div class="w-full md:w-96">
                    <Input 
                        v-model="search" 
                        placeholder="Search by title, cuisine..." 
                        class="glass border-white/10 text-white rounded-2xl h-12"
                    />
                </div>
            </div>

            <!-- Loading State -->
            <div v-if="loading" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
                <div v-for="i in 8" :key="i" class="glass rounded-3xl h-64 animate-pulse"></div>
            </div>

            <!-- Recipes Grid -->
            <div v-else-if="recipes.length > 0" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
                <RecipeCard v-for="recipe in recipes" :key="recipe.id" :recipe="recipe" />
            </div>

            <!-- Empty State -->
            <div v-else class="text-center py-24 glass rounded-3xl">
                <div class="text-6xl mb-4">🔍</div>
                <h3 class="text-xl font-bold text-white mb-2">No recipes found</h3>
                <p class="text-gray-400 mb-8">Try searching for something else or generate your own!</p>
                <Link :href="route('recipes.create')" class="btn-premium inline-block px-8 py-3 rounded-2xl">
                    Create New Recipe ✨
                </Link>
            </div>
        </div>
    </AppLayout>
</template>
