<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import RecipeCard from '@/components/Recipes/RecipeCard.vue';
import { ref, onMounted, watch } from 'vue';
import { Input } from '@/components/ui/input';
import axios from '@/lib/axios';
import { route } from '@/lib/route';

interface Recipe {
    id: number;
    title: string;
    slug: string;
    description: string;
    image: string | null;
    cuisine: string;
    difficulty: string;
    prep_time: number;
    cook_time: number;
}

const recipes = ref<Recipe[]>([]);
const loading = ref(true);
const search = ref('');
const filters = ref({
    cuisine: '',
    difficulty: '',
    maxTime: '',
    minRating: 0,
});
const showFilters = ref(false);

const fetchRecipes = async () => {
    loading.value = true;
    try {
        const params: any = { search: search.value };
        if (filters.value.cuisine) params.cuisine = filters.value.cuisine;
        if (filters.value.difficulty) params.difficulty = filters.value.difficulty;
        if (filters.value.maxTime) params.max_time = filters.value.maxTime;
        if (filters.value.minRating > 0) params.min_rating = filters.value.minRating;

        const response = await axios.get('/recipes', { params });
        recipes.value = response.data.data || response.data || [];
    } catch (error) {
        console.error('Failed to fetch recipes:', error);
        recipes.value = [];
    } finally {
        loading.value = false;
    }
};

onMounted(fetchRecipes);

// Debounced search
let searchTimeout: any;
watch([search, filters], () => {
    clearTimeout(searchTimeout);
    searchTimeout = setTimeout(fetchRecipes, 500);
}, { deep: true });

const breadcrumbs = [
    { title: 'Dashboard', href: route('dashboard') },
    { title: 'Recipes', href: route('recipes.index') },
];
</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbs">
        <Head title="Browse Recipes" />

        <div class="py-12 px-6 max-w-7xl mx-auto">
            <div class="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
                <div>
                    <h1 class="text-4xl font-bold text-white mb-2">Explore <span class="text-gradient">Recipes</span></h1>
                    <p class="text-gray-400">Discover delicious meals generated by AI.</p>
                </div>

                <div class="flex gap-4 w-full md:w-auto">
                    <div class="flex-1 md:w-96">
                        <Input
                            v-model="search"
                            placeholder="Search by title, cuisine..."
                            class="glass border-white/10 text-white rounded-2xl h-12"
                        />
                    </div>
                    <button
                        @click="showFilters = !showFilters"
                        class="px-6 py-3 glass border border-white/10 rounded-2xl text-white hover:bg-white/10 transition-colors"
                    >
                        🔍 Filters
                    </button>
                </div>
            </div>

            <!-- Advanced Filters -->
            <div v-if="showFilters" class="glass p-6 rounded-2xl mb-8 animate-in slide-in-from-top-4 duration-300">
                <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
                    <div>
                        <label class="block text-sm font-medium text-gray-400 mb-2">Cuisine</label>
                        <select v-model="filters.cuisine" class="w-full bg-white/5 border border-white/10 text-white rounded-xl p-3 outline-none focus:border-orange-500/50">
                            <option value="">All Cuisines</option>
                            <option>Italian</option>
                            <option>Mexican</option>
                            <option>Asian</option>
                            <option>Mediterranean</option>
                            <option>French</option>
                            <option>Indian</option>
                            <option>Middle Eastern</option>
                            <option>American</option>
                        </select>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-400 mb-2">Difficulty</label>
                        <select v-model="filters.difficulty" class="w-full bg-white/5 border border-white/10 text-white rounded-xl p-3 outline-none focus:border-orange-500/50">
                            <option value="">All Levels</option>
                            <option>easy</option>
                            <option>medium</option>
                            <option>hard</option>
                        </select>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-400 mb-2">Max Time (min)</label>
                        <select v-model="filters.maxTime" class="w-full bg-white/5 border border-white/10 text-white rounded-xl p-3 outline-none focus:border-orange-500/50">
                            <option value="">Any Time</option>
                            <option value="15">15 minutes</option>
                            <option value="30">30 minutes</option>
                            <option value="60">1 hour</option>
                            <option value="120">2 hours</option>
                        </select>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-400 mb-2">Min Rating</label>
                        <select v-model.number="filters.minRating" class="w-full bg-white/5 border border-white/10 text-white rounded-xl p-3 outline-none focus:border-orange-500/50">
                            <option :value="0">Any Rating</option>
                            <option :value="3">3+ Stars</option>
                            <option :value="4">4+ Stars</option>
                            <option :value="5">5 Stars</option>
                        </select>
                    </div>
                </div>
                <div class="mt-4 flex justify-end">
                    <button
                        @click="filters = { cuisine: '', difficulty: '', maxTime: '', minRating: 0 }; fetchRecipes()"
                        class="px-4 py-2 text-sm text-gray-400 hover:text-white transition-colors"
                    >
                        Clear Filters
                    </button>
                </div>
            </div>

            <!-- Loading State -->
            <div v-if="loading" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
                <div v-for="i in 8" :key="i" class="glass rounded-3xl h-64 animate-pulse"></div>
            </div>

            <!-- Recipes Grid -->
            <div v-else-if="recipes.length > 0" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
                <RecipeCard v-for="recipe in recipes" :key="recipe.id" :recipe="recipe" />
            </div>

            <!-- Empty State -->
            <div v-else class="text-center py-24 glass rounded-3xl">
                <div class="text-6xl mb-4">🔍</div>
                <h3 class="text-xl font-bold text-white mb-2">No recipes found</h3>
                <p class="text-gray-400 mb-8">Try searching for something else or generate your own!</p>
                <Link :href="route('recipes.create')" class="btn-premium inline-block px-8 py-3 rounded-2xl">
                    Create New Recipe ✨
                </Link>
            </div>
        </div>
    </AppLayout>
</template>
