<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $collection->name }} - Cookbook</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            padding: 40px;
        }
        .cover {
            text-align: center;
            padding: 100px 40px;
            border-bottom: 5px solid #f59e0b;
            margin-bottom: 40px;
        }
        .cover h1 {
            font-size: 48px;
            color: #1f2937;
            margin-bottom: 20px;
        }
        .cover p {
            font-size: 18px;
            color: #6b7280;
        }
        .recipe {
            page-break-inside: avoid;
            margin-bottom: 50px;
            padding-bottom: 30px;
            border-bottom: 2px solid #e5e7eb;
        }
        .recipe h2 {
            font-size: 28px;
            color: #f59e0b;
            margin-bottom: 10px;
        }
        .recipe-meta {
            color: #6b7280;
            font-size: 14px;
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 25px;
        }
        .section h3 {
            font-size: 20px;
            color: #1f2937;
            margin-bottom: 15px;
            border-left: 4px solid #f59e0b;
            padding-left: 10px;
        }
        .ingredients-list, .instructions-list {
            list-style: none;
        }
        .ingredients-list li {
            padding: 8px;
            margin-bottom: 5px;
            background: #f9fafb;
            border-left: 3px solid #10b981;
            padding-left: 15px;
        }
        .instructions-list li {
            padding: 12px;
            margin-bottom: 10px;
            background: #f9fafb;
            border-left: 3px solid #3b82f6;
            padding-left: 25px;
            position: relative;
            counter-increment: step-counter;
        }
        .instructions-list {
            counter-reset: step-counter;
        }
        .instructions-list li::before {
            content: counter(step-counter);
            position: absolute;
            left: -15px;
            top: 12px;
            background: #3b82f6;
            color: white;
            width: 28px;
            height: 28px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            font-size: 14px;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #e5e7eb;
            text-align: center;
            color: #9ca3af;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="cover">
        <h1>{{ $collection->name }}</h1>
        @if($collection->description)
        <p>{{ $collection->description }}</p>
        @endif
        <p style="margin-top: 20px; font-size: 14px;">{{ $collection->recipes->count() }} Recipes</p>
    </div>

    @foreach($collection->recipes as $recipe)
    <div class="recipe">
        <h2>{{ $recipe->title }}</h2>
        <div class="recipe-meta">
            {{ $recipe->cuisine }} • {{ ucfirst($recipe->difficulty) }} •
            {{ $recipe->prep_time + $recipe->cook_time }} minutes •
            {{ $recipe->servings }} servings
        </div>

        @if($recipe->description)
        <p style="font-style: italic; color: #4b5563; margin-bottom: 20px;">{{ $recipe->description }}</p>
        @endif

        <div class="section">
            <h3>Ingredients</h3>
            <ul class="ingredients-list">
                @foreach($recipe->ingredients as $ingredient)
                <li>
                    <strong>{{ $ingredient['amount'] ?? '' }} {{ $ingredient['unit'] ?? '' }}</strong>
                    {{ $ingredient['item'] ?? '' }}
                </li>
                @endforeach
            </ul>
        </div>

        <div class="section">
            <h3>Instructions</h3>
            <ol class="instructions-list">
                @foreach($recipe->instructions as $instruction)
                <li>{{ $instruction }}</li>
                @endforeach
            </ol>
        </div>
    </div>
    @endforeach

    <div class="footer">
        <p>Generated by AI-Powered Recipe Generator</p>
        <p>{{ now()->format('F j, Y') }}</p>
    </div>
</body>
</html>
