<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import RecipeCard from '@/components/Recipes/RecipeCard.vue';
import { ref, watch } from 'vue';
import { Input } from '@/components/ui/input';

const props = defineProps<{
    recipes: {
        data: any[];
        links: any[];
    },
    filters: {
        search?: string;
    }
}>();

const search = ref(props.filters.search || '');

watch(search, (value) => {
    router.get(route('recipes.index'), { search: value }, { preserveState: true, replace: true });
});
</script>

<template>
    <AppLayout>
        <Head title="Browse Recipes" />

        <div class="py-12 px-6 max-w-7xl mx-auto">
            <div class="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
                <div>
                    <h1 class="text-4xl font-bold text-white mb-2">Explore <span class="text-gradient">Recipes</span></h1>
                    <p class="text-gray-400">Discover delicious meals generated by AI.</p>
                </div>
                
                <div class="w-full md:w-96">
                    <Input 
                        v-model="search" 
                        placeholder="Search by title, cuisine..." 
                        class="glass border-white/10 text-white rounded-2xl h-12"
                    />
                </div>
            </div>

            <div v-if="recipes.data.length > 0" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
                <RecipeCard v-for="recipe in recipes.data" :key="recipe.id" :recipe="recipe" />
            </div>

            <div v-else class="text-center py-24 glass rounded-3xl">
                <div class="text-6xl mb-4">🔍</div>
                <h3 class="text-xl font-bold text-white mb-2">No recipes found</h3>
                <p class="text-gray-400 mb-8">Try searching for something else or generate your own!</p>
                <Link :href="route('recipes.create')" class="btn-premium inline-block">
                    Create New Recipe
                </Link>
            </div>
            
            <!-- Simple Pagination placeholder -->
            <div v-if="recipes.data.length > 0" class="mt-12 flex justify-center gap-2">
                <template v-for="link in recipes.links" :key="link.label">
                    <Link 
                        :href="link.url || '#'" 
                        v-html="link.label"
                        :class="[
                            'px-4 py-2 rounded-xl text-sm transition-all',
                            link.active ? 'bg-orange-500 text-white' : 'glass text-gray-400 hover:bg-white/10',
                            !link.url && 'opacity-50 cursor-not-allowed'
                        ]"
                    />
                </template>
            </div>
        </div>
    </AppLayout>
</template>
